from __future__ import annotations

from bridge.sync import (
    SOURCE_IMAGE_LEFT,
    SOURCE_IMAGE_RIGHT,
    SOURCE_IMAGE_TOP,
    SOURCE_JOINT_LEFT,
    SOURCE_JOINT_RIGHT,
    SOURCE_ODOM,
)


CAMERA_SOURCES = (
    SOURCE_IMAGE_LEFT,
    SOURCE_IMAGE_RIGHT,
    SOURCE_IMAGE_TOP,
)

STATE_SOURCES = (
    SOURCE_JOINT_LEFT,
    SOURCE_JOINT_RIGHT,
    SOURCE_ODOM,
)

ALL_REQUIRED_SOURCES = CAMERA_SOURCES + STATE_SOURCES
