policy:
  type: streaming_act
  path: ../../outputs/train/zeno-ai/CleanTableTopDelayedToolChoice/streaming-act-prism
  device: cuda
  load_device: null
  n_action_steps: 1
  state_dim: 17
  action_dim: 17
  arm_dof: 7
  base_action_dim: 3
  state_key: observation.state
  action_key: action
  image_keys:
    left: observation.images.realsense_left
    right: observation.images.realsense_right
    top: observation.images.realsense_top

runtime:
  control_hz: 30.0

image:
  width: 224
  height: 224
  color_order: rgb

ros:
  node_name: zeno_streaming_act_prism_deploy
  queue_size: 1
  topics:
    image_left: /realsense_left/color/image_raw/compressed
    image_right: /realsense_right/color/image_raw/compressed
    image_top: /realsense_top/color/image_raw/compressed
    joint_state_left: /robot/arm_left/joint_states_single
    joint_state_right: /robot/arm_right/joint_states_single
    odom: /ranger_base_node/odom
    cmd_vel: /robot/base/vla_cmd_vel
    cmd_joint_left: /robot/arm_left/vla_joint_cmd
    cmd_joint_right: /robot/arm_right/vla_joint_cmd
  joint_names_left:
    name:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - gripper
  joint_names_right:
    name:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - gripper

command:
  publish_base: true
  publish_arms: true
  max_linear_x: 1.0
  max_linear_y: 1.0
  max_angular_z: 3.14
