policy:
  type: act
  path: ../../outputs/train/zeno-ai/wholebody_hanger_stage3_v30/act/20260408_153316/checkpoints/050000
  device: cuda
  load_device: null
  n_action_steps: 1
  state_dim: 17
  action_dim: 17
  arm_dof: 7
  base_action_dim: 3
  state_key: observation.state
  action_key: action
  image_keys:
    left: observation.images.realsense_left
    right: observation.images.realsense_right
    top: observation.images.realsense_top
  use_path_signature: true
  use_delta_signature: true
  signature_depth: 3
  signature_dim: 5219
  signature_backend: auto

runtime:
  control_hz: 20.0

image:
  width: 224
  height: 224
  color_order: rgb

ros:
  node_name: zeno_act_deploy
  queue_size: 1
  topics:
    image_left: /realsense_left/color/image_raw/compressed
    image_right: /realsense_right/color/image_raw/compressed
    image_top: /realsense_top/color/image_raw/compressed
    joint_state_left: /robot/arm_left/joint_states_single
    joint_state_right: /robot/arm_right/joint_states_single
    odom: /ranger_base_node/odom
    cmd_vel: /deploy/cmd_vel
    cmd_joint_left: /deploy/arm_left/joint_states
    cmd_joint_right: /deploy/arm_right/joint_states
  joint_names_left:
    name:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - gripper
  joint_names_right:
    name:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - gripper

command:
  publish_base: true
  publish_arms: true
  max_linear_x: 0.20
  max_linear_y: 0.20
  max_angular_z: 0.40
