train:
  dataset_root: "data/zeno-ai/CleanTableTopDelayedToolChoice"
  dataset_repo_id: "zeno-ai/CleanTableTopDelayedToolChoice"
  output_root: "outputs/train/zeno-ai/CleanTableTopDelayedToolChoice/diffusion"
  resume: false
  job_name: "diffusion"
  wandb_project: "CleanTableTopDelayedToolChoice"
  wandb_mode: "online"
  device: "cuda"
  use_amp: true
  amp_dtype: "auto"
  steps: 50000
  batch_size: 8
  num_workers: 24
  dataloader_persistent_workers: true
  dataloader_prefetch_factor: 4
  video_backend: "torchcodec"
  torch_sharing_strategy: "file_system"
  torchcodec_decoder_cache_size: 32
  enable_filtered_hf_cache: true
  seed: 42
  log_freq: 100
  save_freq: 5000
  eval_freq: -1
  test_ratio: 0
  split_seed: 42
  split_shuffle: true
  n_obs_steps: 2
  horizon: 104
  n_action_steps: 100
  drop_n_last_frames: 3
  enable_wandb: true
  wandb_console: "off"
  wandb_service_wait: 10

eval:
  train_output_root: "outputs/train/zeno-ai/CleanTableTopDelayedToolChoice/diffusion"
  output_dir: "outputs/eval/zeno-ai/CleanTableTopDelayedToolChoice/diffusion/{run_tag}"
  eval_split: "test"
  test_ratio: 0
  split_seed: 42
  split_shuffle: true
  max_episodes: 20
  max_steps_per_episode: null
  seed: 42
  device: "cuda"
  n_action_steps: 50
